export { GlobalHighlightService } from './GlobalHighlightService';
export { HighlightBatchOps } from './HighlightBatchOps';
export { HighlightCommentResolver } from './HighlightCommentResolver';
export { HighlightDataService } from './HighlightDataService';
export { HighlightExtractor } from './HighlightExtractor';
export { HighlightIndexFileWatcher } from './HighlightIndexFileWatcher';
export { HighlightIndexStore } from './HighlightIndexStore';
export { HighlightIndexer } from './HighlightIndexer';
export * from './HighlightMatchStrategies';
export { HighlightMatcher } from './HighlightMatcher';
